/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Composer: typeof import('./src/components/Composer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HomeActions: typeof import('./src/components/home/HomeActions.vue')['default']
    HomeGreeting: typeof import('./src/components/home/HomeGreeting.vue')['default']
    HomeHeader: typeof import('./src/components/home/HomeHeader.vue')['default']
    HomeLayout: typeof import('./src/components/home/HomeLayout.vue')['default']
    Launcher: typeof import('./src/components/Launcher.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    ModernButton: typeof import('./src/components/common/ModernButton.vue')['default']
    ModernCard: typeof import('./src/components/common/ModernCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarConversations: typeof import('./src/components/sidebar/SidebarConversations.vue')['default']
    SidebarHeader: typeof import('./src/components/sidebar/SidebarHeader.vue')['default']
    SidebarNavigation: typeof import('./src/components/sidebar/SidebarNavigation.vue')['default']
  }
}
