-- 测试数据库初始化脚本
-- 包含必要的表结构和测试数据 (H2兼容)

-- 基本的表结构（H2兼容版本）
DROP TABLE IF EXISTS config CASCADE;
CREATE TABLE config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  config_value VARCHAR(100),
  url VARCHAR(500)
);

-- 聊天表
DROP TABLE IF EXISTS chat CASCADE;
CREATE TABLE chat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  userid BIGINT NOT NULL,
  adminid BIGINT,
  ask CLOB,
  reply CLOB,
  isreply INTEGER
);

-- 到期提醒表
DROP TABLE IF EXISTS daoqitixing CASCADE;
CREATE TABLE daoqitixing (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  yonghuzhanghao VARCHAR(200),
  yonghuxingming VARCHAR(200),
  touxiang CLOB,
  huiyuankahao VARCHAR(200),
  youxiaoqizhi DATE,
  tixingshijian TIMESTAMP,
  beizhu VARCHAR(200)
);

-- 健身课程讨论表
DROP TABLE IF EXISTS discussjianshenkecheng CASCADE;
CREATE TABLE discussjianshenkecheng (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  refid BIGINT NOT NULL,
  userid BIGINT NOT NULL,
  avatarurl CLOB,
  nickname VARCHAR(200),
  content CLOB NOT NULL,
  reply CLOB,
  sfsh VARCHAR(200) DEFAULT '待审核',
  clicktime TIMESTAMP
);

-- 会员卡表
DROP TABLE IF EXISTS huiyuanka CASCADE;
CREATE TABLE huiyuanka (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  huiyuankamingcheng VARCHAR(200) NOT NULL,
  tupian CLOB,
  youxiaoqi VARCHAR(200) NOT NULL,
  jiage INTEGER,
  shiyongshuoming CLOB,
  huiyuankaxiangqing CLOB
);

-- 会员卡购买表
DROP TABLE IF EXISTS huiyuankagoumai CASCADE;
CREATE TABLE huiyuankagoumai (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  huiyuankahao VARCHAR(200),
  huiyuankamingcheng VARCHAR(200),
  tupian CLOB,
  youxiaoqi VARCHAR(200),
  jiage INTEGER,
  goumairiqi DATE,
  yonghuzhanghao VARCHAR(200),
  yonghuxingming VARCHAR(200),
  shoujihaoma VARCHAR(200),
  ispay VARCHAR(200) DEFAULT '未支付',
  UNIQUE (huiyuankahao)
);

-- 会员续费表
DROP TABLE IF EXISTS huiyuanxufei CASCADE;
CREATE TABLE huiyuanxufei (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  yonghuzhanghao VARCHAR(200),
  yonghuxingming VARCHAR(200),
  touxiang CLOB,
  jiaofeibianhao VARCHAR(200),
  huiyuankamingcheng VARCHAR(200) NOT NULL,
  youxiaoqi VARCHAR(200),
  jiage DOUBLE PRECISION,
  xufeishijian TIMESTAMP,
  ispay VARCHAR(200) DEFAULT '未支付',
  UNIQUE (jiaofeibianhao)
);

-- 健身教练表
DROP TABLE IF EXISTS jianshenjiaolian CASCADE;
CREATE TABLE jianshenjiaolian (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  jiaoliangonghao VARCHAR(200) NOT NULL,
  mima VARCHAR(200) NOT NULL,
  password_hash VARCHAR(255),
  jiaolianxingming VARCHAR(200),
  touxiang CLOB,
  xingbie VARCHAR(200),
  nianling INTEGER,
  shoujihaoma VARCHAR(200),
  zhiyejieshao CLOB,
  status INTEGER DEFAULT 0,
  failed_login_attempts INTEGER DEFAULT 0,
  lock_until TIMESTAMP
);

-- 健身课程表
DROP TABLE IF EXISTS jianshenkecheng CASCADE;
CREATE TABLE jianshenkecheng (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  kechengmingcheng VARCHAR(200) NOT NULL,
  kechengleixing VARCHAR(200) NOT NULL,
  tupian CLOB,
  shangkeshijian TIMESTAMP NOT NULL,
  shangkedidian VARCHAR(200) NOT NULL,
  kechengjiage DOUBLE PRECISION,
  kechengjianjie CLOB,
  kechengshipin CLOB,
  shangkejihua CLOB,
  shangkeshichang INTEGER,
  baomingrenshu INTEGER DEFAULT 0,
  yuyuerenshu INTEGER DEFAULT 0,
  status INTEGER DEFAULT 0,
  jiaoliangonghao VARCHAR(200),
  jiaolianxingming VARCHAR(200),
  clicktime TIMESTAMP,
  clicknum INTEGER DEFAULT 0,
  discussnum INTEGER DEFAULT 0,
  storeupnum INTEGER DEFAULT 0
);

-- 健身器材表
DROP TABLE IF EXISTS jianshenqicai CASCADE;
CREATE TABLE jianshenqicai (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  qicaimingcheng VARCHAR(200) NOT NULL,
  qicaileixing VARCHAR(200) NOT NULL,
  tupian CLOB,
  qicaizhuangtai VARCHAR(200),
  shuliang INTEGER,
  weizhi VARCHAR(200),
  qicaijianjie CLOB,
  status INTEGER DEFAULT 0
);

-- 新闻资讯表
DROP TABLE IF EXISTS news CASCADE;
CREATE TABLE news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(200) NOT NULL,
  introduction CLOB,
  picture CLOB,
  content CLOB
);

-- 收藏表
DROP TABLE IF EXISTS storeup CASCADE;
CREATE TABLE storeup (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  userid BIGINT NOT NULL,
  refid BIGINT NOT NULL,
  tablename VARCHAR(200),
  name VARCHAR(200),
  picture CLOB,
  type VARCHAR(200) DEFAULT '1',
  inteltype VARCHAR(200)
);

-- 课程预约表
DROP TABLE IF EXISTS yuyuekecheng CASCADE;
CREATE TABLE yuyuekecheng (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  kechengmingcheng VARCHAR(200),
  kechengleixing VARCHAR(200),
  tupian CLOB,
  shangkeshijian TIMESTAMP,
  shangkedidian VARCHAR(200),
  kechengjiage DOUBLE PRECISION,
  yonghuzhanghao VARCHAR(200),
  yonghuxingming VARCHAR(200),
  shoujihaoma VARCHAR(200),
  yuyueshijian TIMESTAMP,
  beizhu VARCHAR(200),
  sfsh VARCHAR(200) DEFAULT '待审核',
  shhf CLOB
);

-- 课程评分表
DROP TABLE IF EXISTS yuyuekecheng_pingjia CASCADE;
CREATE TABLE yuyuekecheng_pingjia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  refid BIGINT NOT NULL,
  userid BIGINT NOT NULL,
  avatarurl CLOB,
  nickname VARCHAR(200),
  content CLOB NOT NULL,
  reply CLOB,
  sfsh VARCHAR(200) DEFAULT '待审核',
  clicktime TIMESTAMP
);

-- 器材预约表
DROP TABLE IF EXISTS yuyueqicai CASCADE;
CREATE TABLE yuyueqicai (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  qicaimingcheng VARCHAR(200),
  qicaileixing VARCHAR(200),
  tupian CLOB,
  yuyueshijian TIMESTAMP,
  yuyueshichang INTEGER,
  yonghuzhanghao VARCHAR(200),
  yonghuxingming VARCHAR(200),
  shoujihaoma VARCHAR(200),
  beizhu VARCHAR(200),
  sfsh VARCHAR(200) DEFAULT '待审核',
  shhf CLOB
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_chat_userid ON chat(userid);
CREATE INDEX IF NOT EXISTS idx_daoqitixing_yonghuzhanghao ON daoqitixing(yonghuzhanghao);
CREATE INDEX IF NOT EXISTS idx_discussjianshenkecheng_refid ON discussjianshenkecheng(refid);
CREATE INDEX IF NOT EXISTS idx_discussjianshenkecheng_userid ON discussjianshenkecheng(userid);
CREATE INDEX IF NOT EXISTS idx_huiyuankagoumai_yonghuzhanghao ON huiyuankagoumai(yonghuzhanghao);
CREATE INDEX IF NOT EXISTS idx_huiyuanxufei_yonghuzhanghao ON huiyuanxufei(yonghuzhanghao);
CREATE INDEX IF NOT EXISTS idx_jianshenjiaolian_jiaoliangonghao ON jianshenjiaolian(jiaoliangonghao);
CREATE INDEX IF NOT EXISTS idx_jianshenkecheng_kechengleixing ON jianshenkecheng(kechengleixing);
CREATE INDEX IF NOT EXISTS idx_jianshenkecheng_status ON jianshenkecheng(status);
CREATE INDEX IF NOT EXISTS idx_jianshenqicai_qicaileixing ON jianshenqicai(qicaileixing);
CREATE INDEX IF NOT EXISTS idx_news_addtime ON news(addtime);
CREATE INDEX IF NOT EXISTS idx_storeup_userid ON storeup(userid);
CREATE INDEX IF NOT EXISTS idx_storeup_refid ON storeup(refid);
CREATE INDEX IF NOT EXISTS idx_storeup_tablename ON storeup(tablename);
CREATE INDEX IF NOT EXISTS idx_yuyuekecheng_yonghuzhanghao ON yuyuekecheng(yonghuzhanghao);
CREATE INDEX IF NOT EXISTS idx_yuyuekecheng_sfsh ON yuyuekecheng(sfsh);
CREATE INDEX IF NOT EXISTS idx_yuyueqicai_yonghuzhanghao ON yuyueqicai(yonghuzhanghao);
CREATE INDEX IF NOT EXISTS idx_yuyueqicai_sfsh ON yuyueqicai(sfsh);

-- 管理员用户表
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255),
  failed_login_attempts INTEGER DEFAULT 0,
  lock_until TIMESTAMP,
  image VARCHAR(200),
  role VARCHAR(100) DEFAULT '管理员',
  status INTEGER DEFAULT 0,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS yonghu CASCADE;
CREATE TABLE yonghu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  yonghuzhanghao VARCHAR(200) NOT NULL,
  mima VARCHAR(200) NOT NULL,
  password_hash VARCHAR(255),
  yonghuxingming VARCHAR(200),
  touxiang CLOB,
  xingbie VARCHAR(200),
  shengao VARCHAR(200),
  tizhong VARCHAR(200),
  shoujihaoma VARCHAR(200),
  huiyuankahao VARCHAR(200),
  huiyuankamingcheng VARCHAR(200),
  youxiaoqizhi VARCHAR(200),
  status INTEGER DEFAULT 0,
  failed_login_attempts INTEGER DEFAULT 0,
  lock_until TIMESTAMP
);

-- 创建站内消息表
DROP TABLE IF EXISTS messages CASCADE;
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  userid BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content CLOB NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'system',
  isread INTEGER NOT NULL DEFAULT 0,
  related_type VARCHAR(100),
  related_id BIGINT
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_messages_userid ON messages(userid);
CREATE INDEX IF NOT EXISTS idx_messages_isread ON messages(isread);
CREATE INDEX IF NOT EXISTS idx_messages_type ON messages(type);
CREATE INDEX IF NOT EXISTS idx_messages_related ON messages(related_type, related_id);

-- 确保管理员用户存在
INSERT INTO users (id, username, password, password_hash, failed_login_attempts, image, role, status, addtime)
VALUES (1, 'admin', 'admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lbdxp7O.7C0XJ8Eo', 0, 'upload/image1.jpg', '管理员', 0, CURRENT_TIMESTAMP);

INSERT INTO users (id, username, password, password_hash, failed_login_attempts, image, role, status, addtime)
VALUES (2, 'manager', '123456', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lbdxp7O.7C0XJ8Eo', 0, 'upload/image2.jpg', '管理员', 0, CURRENT_TIMESTAMP);

-- 确保测试用户存在
INSERT INTO yonghu (id, yonghuzhanghao, mima, password_hash, yonghuxingming, touxiang, xingbie, shengao, tizhong, shoujihaoma, huiyuankahao, huiyuankamingcheng, youxiaoqizhi, status, failed_login_attempts, addtime)
VALUES (999999, 'testuser', '123456', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lbdxp7O.7C0XJ8Eo', '测试用户', 'upload/test.jpg', '男', '170', '65', '13800138000', 'VIP001', 'VIP会员', '2024-12-31', 0, 0, CURRENT_TIMESTAMP);

INSERT INTO yonghu (id, yonghuzhanghao, mima, password_hash, yonghuxingming, touxiang, xingbie, shengao, tizhong, shoujihaoma, huiyuankahao, huiyuankamingcheng, youxiaoqizhi, status, failed_login_attempts, addtime)
VALUES (999998, 'testuser2', '123456', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lbdxp7O.7C0XJ8Eo', '测试用户2', 'upload/test2.jpg', '女', '165', '55', '13800138001', 'VIP002', '普通会员', '2024-12-31', 0, 0, CURRENT_TIMESTAMP);

-- 创建token表
DROP TABLE IF EXISTS token CASCADE;
CREATE TABLE token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userid BIGINT NOT NULL,
  username VARCHAR(100) NOT NULL,
  tablename VARCHAR(100),
  role VARCHAR(100),
  token VARCHAR(200) NOT NULL,
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiratedtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 创建operation_log表
DROP TABLE IF EXISTS operation_log CASCADE;
CREATE TABLE operation_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userid BIGINT NOT NULL,
  username VARCHAR(100) NOT NULL,
  table_name VARCHAR(100),
  operation_type VARCHAR(50) NOT NULL,
  content VARCHAR(500),
  ip VARCHAR(50),
  addtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 添加一些测试数据

-- 配置文件数据
INSERT INTO config (name, config_value, url) VALUES
('site_name', '健身房管理系统', NULL),
('site_logo', 'upload/logo.jpg', NULL),
('contact_phone', '400-888-8888', NULL);

-- 聊天数据
INSERT INTO chat (userid, adminid, ask, reply, isreply, addtime) VALUES
(999999, 1, '请问如何预约课程？', '您可以在课程列表中选择课程并点击预约按钮。', 1, CURRENT_TIMESTAMP),
(999998, 1, '会员卡如何续费？', '请到前台办理续费手续。', 1, CURRENT_TIMESTAMP);

-- 会员卡数据
INSERT INTO huiyuanka (huiyuankamingcheng, tupian, youxiaoqi, jiage, shiyongshuoming, huiyuankaxiangqing, addtime) VALUES
('VIP年卡', 'upload/vip_card.jpg', '一年', 3600, '全年无限次使用', 'VIP会员享受所有课程免费', CURRENT_TIMESTAMP),
('普通月卡', 'upload/monthly_card.jpg', '一个月', 300, '每月无限次使用', '普通会员享受基础课程', CURRENT_TIMESTAMP);

-- 健身课程数据
INSERT INTO jianshenkecheng (kechengmingcheng, kechengleixing, tupian, shangkeshijian, shangkedidian, kechengjiage, kechengjianjie, kechengshipin, shangkejihua, shangkeshichang, baomingrenshu, yuyuerenshu, status, addtime) VALUES
('瑜伽入门课程', '瑜伽', 'upload/yoga.jpg', '2024-12-01 09:00:00', '1号教室', 50.0, '适合初学者的瑜伽课程', 'upload/yoga_video.mp4', '热身+基本姿势+冥想', 90, 20, 15, 0, CURRENT_TIMESTAMP),
('力量训练课程', '力量训练', 'upload/strength.jpg', '2024-12-01 14:00:00', '2号训练室', 80.0, '全面提升肌肉力量的训练课程', 'upload/strength_video.mp4', '热身+杠铃训练+器械训练+拉伸', 120, 15, 12, 0, CURRENT_TIMESTAMP);

-- 健身器材数据
INSERT INTO jianshenqicai (qicaimingcheng, qicaileixing, tupian, qicaizhuangtai, shuliang, weizhi, qicaijianjie, status, addtime) VALUES
('跑步机', '有氧器械', 'upload/treadmill.jpg', '可用', 5, '1号训练区', '专业跑步机，支持多种训练模式', 0, CURRENT_TIMESTAMP),
('哑铃组', '力量器械', 'upload/dumbbells.jpg', '可用', 10, '力量训练区', '5-50kg哑铃套装', 0, CURRENT_TIMESTAMP);

-- 新闻资讯数据
INSERT INTO news (title, introduction, picture, content, addtime) VALUES
('健身房冬季活动开始啦！', '冬季健身季来临，健身房推出多项优惠活动', 'upload/news1.jpg', '为了让更多会员在冬季保持健身习惯，健身房推出了一系列优惠活动...', CURRENT_TIMESTAMP),
('新年会员卡续费优惠', '新年期间续费会员卡享8折优惠', 'upload/news2.jpg', '2024年新年期间，续费任何类型会员卡均可享受8折优惠...', CURRENT_TIMESTAMP);

-- 课程预约数据
INSERT INTO yuyuekecheng (kechengmingcheng, kechengleixing, tupian, shangkeshijian, shangkedidian, kechengjiage, yonghuzhanghao, yonghuxingming, shoujihaoma, yuyueshijian, beizhu, sfsh, addtime) VALUES
('瑜伽入门课程', '瑜伽', 'upload/yoga.jpg', '2024-12-01 09:00:00', '1号教室', 50.0, 'testuser', '测试用户', '13800138000', CURRENT_TIMESTAMP, '希望学习基础姿势', '待审核', CURRENT_TIMESTAMP);

-- 器材预约数据
INSERT INTO yuyueqicai (qicaimingcheng, qicaileixing, tupian, yuyueshijian, yuyueshichang, yonghuzhanghao, yonghuxingming, shoujihaoma, beizhu, sfsh, addtime) VALUES
('跑步机', '有氧器械', 'upload/treadmill.jpg', CURRENT_TIMESTAMP, 60, 'testuser', '测试用户', '13800138000', '需要使用跑步机进行有氧训练', '待审核', CURRENT_TIMESTAMP);

-- 会员卡购买数据
INSERT INTO huiyuankagoumai (huiyuankahao, huiyuankamingcheng, tupian, youxiaoqi, jiage, goumairiqi, yonghuzhanghao, yonghuxingming, shoujihaoma, ispay, addtime) VALUES
('VIP001', 'VIP年卡', 'upload/vip_card.jpg', '一年', 3600, CURRENT_DATE, 'testuser', '测试用户', '13800138000', '已支付', CURRENT_TIMESTAMP);

-- 站内消息数据
INSERT INTO messages (userid, title, content, type, isread, addtime) VALUES
(999999, '欢迎消息', '欢迎使用健身房管理系统！', 'system', 0, CURRENT_TIMESTAMP),
(999999, '会员卡到期提醒', '您的会员卡还有7天到期，请及时续费。', 'reminder', 0, CURRENT_TIMESTAMP),
(999998, '课程预约成功', '您已成功预约2024-01-15的瑜伽课程。', 'system', 1, '2024-01-15 10:00:00');
